### ISSUE TITLE
filter-samples/filter-features: support "negate" filtering option

### ISSUE THREAD

**Issue by jairideout** [qiime2/q2-feature-table#101]
QIIME 1's filtering scripts have an option to negate the filtering operation (i.e. *exclude* instead of *include*). It'd be useful to add that functionality to `filter-samples`/`filter-features`.

This came up on the forum [here](https://forum.qiime2.org/t/removing-deleting-a-single-feature-from-a-feature-table/560).

**Comment by thermokarst** [comment]
FWIW, we can exclude Samples via the SQL clause right now (`--p-where "\"#SampleID\" IS NOT IN ('L1S8')"`), although this would certainly seem easier as an `--exclude` type of flag.

**Comment by jairideout** [comment]
Thanks @thermokarst! I was thinking the option could also apply to index-based filtering so that a simple tsv file can be either positively or negatively filtered.

**Comment by ebolyen** [comment]
Looking at the code, I don't think you can exclude IDs that aren't present in your Metadata object. So if you wanted to just list IDs to not have, you'd still need a file of ALL of the IDs before you could exclude.

**Comment by thermokarst** [comment]
@ebolyen, yep, that makes sense, just wanted to point out that we have some workarounds available for specific cases.

**Comment by jairideout** [comment]
@ebolyen was your comment in response to @thermokarst's SQL query workaround or the index-based filtering from my comment? I think it should be possible to implement for index-based filtering (for an example, see QIIME 1's `filter_otus_from_otu_table.py` with options `--otu_ids_to_exclude_fp` and `--negate_ids_to_exclude`).

**Comment by ebolyen** [comment]
Just a general note that our where clause can only negate samples it
already knew about.
