### ISSUE TITLE
Merging capabilities should not be limited to two objects at a time

### ISSUE THREAD

**Issue by ElDeveloper** [qiime2/q2-feature-table#103]
With `qiime feature-table merge`, users should be able to merge an arbitrary number of tables at a time. Currently the interface only allows for two tables to be merged at a time, which leads to a proliferation of intermediate tables. The same thing applies for `qiime feature-table merge-seq-data`.

**Comment by jairideout** [comment]
[Came up on the forum.](https://forum.qiime2.org/t/from-biom-to-taxa-barplot/1620/4?u=jairideout)
