### ISSUE TITLE
Filter features from a feature-table based on a FASTA file

### ISSUE THREAD

**Issue by ElDeveloper** [qiime2/q2-feature-table#104]
It would be useful if `qiime feature-table filter-features` could also filter features based on a FASTA file. Alternatively filtering based on feature ID would probably accomplish this as well.

**Comment by jairideout** [comment]
> Alternatively filtering based on feature ID would probably accomplish this as well.

This functionality exists, check out [index-based filtering](https://docs.qiime2.org/2017.4/tutorials/filtering/#index-based-filtering) in the filtering tutorial.

**Comment by jairideout** [comment]
In addition to the index-based filtering I mentioned above, it is now possible to filter features from a feature-table using any of the following .qza types: `FeatureData[Taxonomy]`, `FeatureData[Sequence]`, `FeatureData[AlignedSequence]` (added in https://github.com/qiime2/q2-types/pull/125).
