### ISSUE TITLE
Filtering samples from a rarefied table forgets uniform sampling

### ISSUE THREAD

**Issue by ElDeveloper** [qiime2/q2-feature-table#108]
After rarefying a feature table, I filtered some samples and then realized that the uniform sampling property had been lost. I understand this may happen in some cases, but not when you filter samples, this is the command I used:

```
qiime feature-table filter-samples \
--i-table table.even1250.qza \
--p-where 'env_material != "sterile water"' \
--o-filtered-table table.even1250.filtered.qza \
--m-sample-metadata-file mapping-file.txt
```

The types went from:

`FeatureTable[Frequency] % Properties(['uniform-sampling'])` -> `FeatureTable[Frequency]`

**Comment by jairideout** [comment]
:+1:, this is something we intend to support/fix in the near future (there are a couple of framework issues that need resolving before we can move forward). Thanks @ElDeveloper!

**Comment by jairideout** [comment]
Closing as the `uniform-sampling` property was removed from QIIME 2 during this development cycle.
