### ISSUE TITLE
Interactive Sample Detail, question/bug?

### ISSUE THREAD

**Issue by thermokarst** [qiime2/q2-feature-table#110]
Ported from https://github.com/qiime2/qiime2/issues/276 (@antgonza)

During the ASM workshop a user pointed out that the "Sequences Retained: 0 (0.00%)" field is confusing, which I agree. The confusing points are:

- It starts in 0 with 0.0% retained, where it should be 100%, right?
- Once you start moving to the right, it seems to be going up so showing the sequences removed (not retained) and then once you get to around (50%) it starts going up, see screenshot.

![feat-table](https://cloud.githubusercontent.com/assets/274668/26791721/d35e7aea-49cc-11e7-87fa-2e33646bdf59.gif)

**Comment by ebolyen** [comment]
Actually I think the behavior is correct, because we're sampling `0` sequences from all samples, which is still `0`.

And increasing the sampling depth is does not have a monotonic relationship with sequences retained depending on the distribution of reads in each sample.

**Comment by antgonza** [comment]
0: I think the source of confusion is that 0 can be seen as no rarefaction or a rarefaction of 0, nothing selected, right? The part that is confusing is that when is 0, the "Samples Retained" is at 100% (34 samples) while "Sequences retained" are at 0%, so which one is it? BTW I prefer to see 0 as no rarefaction as rarefying at 0 doesn't make sense.

increasing: I think you are right and that's the source of confusion as it's expected to remove the full sample so have a jump on the %. Example below:
![question](https://cloud.githubusercontent.com/assets/2014559/26796221/e02e9ad4-49e5-11e7-80c7-ea1489c2c31f.gif)

**Comment by ebolyen** [comment]
Re: 0, I think your argument makes sense. What if at a sampling depth of `0` we listed both `Samples Retained` and `SequencesRetained` as `N/A`. `0` is kind of this weird intersection where it definitely keeps every sample, so you can see the visualization in a default state, but it also happens to remove every sequence. So while the question we're answering *can* be interpreted consistently with a vacuous truth (100% and 0), it doesn't answer a question the user had in the first place, so `N/A` may avoid the confusion (and still give us a nice default state of what all samples look like with respect to their metadata).

Re: increasing, I'm not sure I understand your example, but is there something we could do to make this relationship with rarefying a little more obvious? It definitely caught me off guard the first time I saw this and I had to think for a bit to understand why it was happening.

**Comment by antgonza** [comment]
0: I understand your argument but then the plot on the right will not make sense (match), right? One option is to replace the 0 in the drag menu to no-rarefaction and then make everything 100%, so when you move to 1, everything else starts acting as expected.

increasing: the attachment was mainly as a reference in case someone is wondering what are we talking about. Anyway, one option might be to join both displays so it's easier to catch both moving, something like (I think the problem is that you are focus in either):
Retaining: XXX features (100%) of 34 samples (100%)

**Comment by ebolyen** [comment]
Re 0: the plot on the right should still be accurate as it doesn't interact with sequences, only samples. So by mapping `0` to `N/A` for the rarefying summaries, we can make it look like what happens when you don't rarefy because it's still the same plot.

Re increasing: I like the idea of combining them.

**Comment by antgonza** [comment]
K, I think we are close to a resolution. If we only have one message then I see 3 options when we select 0:
A. `XXX features (N/A) of 34 samples (N/A)`
or 
B. `N/A features (N/A) of N/A samples (N/A)`
or
C. `XXX features (100%) of 34 samples (100%)`
I prefer C, if possible. Now, I'm OK with leaving 0 as the first option in the drag menu but perhaps replacing 0 for 'no-rarefaction' will be better

**Comment by ebolyen** [comment]
I think there's also another option:
D. `Retaining: N/A`

(Sample and feature statistics for the entire table are on the first tab already, so we don't get much by repeating them in the "no rarefy" case.)

**Comment by antgonza** [comment]
Good point. However, I think having that information in this page adds to the user experience as I personally tend to forget those details (I'm sure I'm not the only one) and having them will help.
