### ISSUE TITLE
Summarize Visualization - Plot Sampling Depth vs Retained Seqs/Samples

### ISSUE THREAD

**Issue by amashchak** [qiime2/q2-feature-table#114]
**Improvement Description**
It would be useful to be able to view the curve of sampling depth against either retained sequences or retained samples. 

**Comments**
This would enable one to better evaluate the cost/benefit trade-off of sampling depth versus retention.

**Comment by lizgehret** [comment]
Closing this as the interactive sample detail achieves this by showing the retained sequences/samples based on the chosen sampling depth.
