### ISSUE TITLE
BUG: summarize extended scroll

### ISSUE THREAD

**Issue by thermokarst** [qiime2/q2-feature-table#115]
**Bug Description**
When viewing the "Overview" tab in a `summarize` visualization, if you click into the detailed HTML views of either "Frequency per sample detail" or "Frequency per feature detail," pressing the back button to get back to the main "Overview" tab doesn't resize the window contents vertically. If the per feature table is long, this causes the "Overview" tab to have an equal height made up of whitespace, which looks pretty awesome, but isn't really useful! 

**Comments**
This isn't related to the `iframe` hackery in q2view, I was able to reproduce this in both q2view and `qiime tools view`.

**Comment by jakereps** [comment]
This might be related to the "tab-*" functionality of `q2templates`. It's using some hackery to communicate between the parent and child iframes.

**Comment by lizgehret** [comment]
Closing as we are not currently able to replicate this issue.
