### ISSUE TITLE
support filtering FeatureData[Sequence]

### ISSUE THREAD

**Issue by jairideout** [qiime2/q2-feature-table#119]
Feature request came up [on the forum](https://forum.qiime2.org/t/filtering-representative-sequences/825). Add a method to support filtering sequences from `FeatureData[Sequence]` artifacts. This is something we'll need for feature parity with QIIME 1.

**Comment by jairideout** [comment]
Came up again on the forum [here](https://forum.qiime2.org/t/filtering-and-then-merging-2-different-runs-same-barcodes-used-in-both-runs/897/1).

**Comment by thermokarst** [comment]
Came up again on the forum [here](https://forum.qiime2.org/t/mock-sample-and-pcr-blanks/1113).
