### ISSUE TITLE
BUG: Can't download FASTA file from tabulate-seqs

### ISSUE THREAD

**Issue by thermokarst** [qiime2/q2-feature-table#120]
The convenience link for downloading the source FASTA [appears to be broken](https://forum.qiime2.org/t/cant-download-fasta-file-from-feature-table-tabulate-seqs/955?u=thermokarst) (at least when used on q2view).

**Comment by thermokarst** [comment]
Update --- this is specifically an issue with q2view and this visualization --- viewing locally via q2cli works as expected.

**Comment by jairideout** [comment]
Fixed in #130 :tada:
