### ISSUE TITLE
Performance issue with summarize and large tables

### ISSUE THREAD

**Issue by ElDeveloper** [qiime2/q2-feature-table#122]
I am running the summarize visualizer on a table with ~300,000 features and 120 samples. This has been running for about 2 hours now. I would have not expected this command to take so long.

Specific code:

```python
import qiime2 as q2
from qiime2.plugins import feature_table

feature_table.visualizers.summarize(q2.Artifact.load('feature-table.qza'),
                                    q2.Metadata.load('mapping-file.tsv'))
```

After talking with @ebolyen and looking at the `TMPDIR`, it seems like the visualizer is getting hung on the feature-level summary.

**Comment by antgonza** [comment]
I just noticed this too, my command:
```
qiime feature-table summarize --i-table biom_table.qza \
   --o-visualization biom_table.qzv \
   --m-sample-metadata-file metaanalysis_map.txt
```
Mine took ~40min for 1,567 samples and 60,461.

I also noticed that the visualization have, IMOO, uninformative categories that might make the processing time larger, for example:
![barcode](https://user-images.githubusercontent.com/2014559/32569246-d4baf6c6-c47d-11e7-8456-b01dc0a86d4f.png)

**Comment by antgonza** [comment]
I just noticed this too, my command:
```
qiime feature-table summarize --i-table biom_table.qza \
   --o-visualization biom_table.qzv \
   --m-sample-metadata-file metaanalysis_map.txt
```
Mine took ~40min for 1,567 samples and 60,461.

I also noticed that the visualization have, IMOO, uninformative categories that might make the processing time larger, for example:
![barcode](https://user-images.githubusercontent.com/2014559/32569246-d4baf6c6-c47d-11e7-8456-b01dc0a86d4f.png)

**Comment by antgonza** [comment]
I just noticed this too, my command:
```
qiime feature-table summarize --i-table biom_table.qza \
   --o-visualization biom_table.qzv \
   --m-sample-metadata-file metaanalysis_map.txt
```
Mine took ~40min for 1,567 samples and 60,461.

I also noticed that the visualization have, IMOO, uninformative categories that might make the processing time larger, for example:
![barcode](https://user-images.githubusercontent.com/2014559/32569246-d4baf6c6-c47d-11e7-8456-b01dc0a86d4f.png)
