### ISSUE TITLE
`feature-table summarize` missing y-axis label

### ISSUE THREAD

**Issue by antgonza** [qiime2/q2-feature-table#128]
When trying to demo the `qiime feature-table summarize` command, we noticed that the y-label was missing.

![image](https://user-images.githubusercontent.com/2014559/29541914-76fdef88-8694-11e7-9824-b9348e4adccc.png)

This could confuse users.

**Comment by antgonza** [comment]
For completeness, both plots in that summary are missing y labels.

**Comment by ebolyen** [comment]
@antgonza, thanks! We've tried to come up with a y-label that makes sense with the x-label and we can't really come up with a satisfying one:

Samples; Frequency per sample
Samples in bin; Frequency per sample
etc

Do you have any suggestions here? Also would you be interested in issuing a PR (or know someone who would be)?

**Comment by antgonza** [comment]
Interesting, it sounds like that if it's hard is cause is not that simple to describe and perhaps useful (plots should be easy to explain the data that you have, right?)? I guess, the question is: how helpful is to have the "Frequency per sample" and "Frequency per feature" plots? In my experience, what's really useful is the "Table summary" & interactive plot. What about merging these 2 into a single tab and remove the rest?

I'm OK working on this, if we can agree on the "new" look ...

**Comment by gregcaporaso** [comment]
I find these plots useful for picking rarefaction depth, and we don't have a similar summary anywhere in this viz so I don't think we should drop the plots. These are histograms, where the values on the x axis are the number of sequences per sample, and the values on the y-axis are numbers of samples (top plot) and number of features (bottom plot). I use these by looking for natural breaks in the per sample counts to help inform my rarefaction depth setting. 

@jairideout suggested setting the y-axis labels to `Number of samples` and `Number of features`, respectively. I think that's a good approach.

**Comment by antgonza** [comment]
@gregcaporaso and @jairideout, just to confirm:
- plot 1, x: "Frequency per sample", y: "Number of samples"
- plot 2, x: "Frequency per feature", y: "Number of features"

**Comment by jairideout** [comment]
Looks good!
