### ISSUE TITLE
colors in bar plot labels doesn't update

### ISSUE THREAD

**Issue by antgonza** [qiime2/q2-feature-table#133]
If you change the pallet it will change the plot but not the label, see below:
![no-color-change](https://user-images.githubusercontent.com/2014559/29733227-65eea1ac-89a9-11e7-8723-eb4989e1aa2a.gif)

**Comment by thermokarst** [comment]
Duplicate of https://github.com/qiime2/q2-taxa/issues/85 (also, the fix is staged for 2017.8).

**Comment by thermokarst** [comment]
Thanks @antgonza!
