### ISSUE TITLE
filter method

### ISSUE THREAD

**Issue by gregcaporaso** [qiime2/q2-feature-table#14]
should filter based on sample metadata/ids, feature metadata/ids, or counts. In QIIME 1, this is a few different scripts - can/should this be reduced to one in QIIME 2?

**Comment by ebolyen** [comment]
This will rely on `TypeMap` to retain the variant-type of `FeatureTable`.

**Comment by nbokulich** [comment]
This is currently the most needed method in Q2, in my opinion. Being able to slice and dice data into subsets and remove samples past QC stages (e.g., low coverage, negatives, controls, mock samples) is vital for most real-life situations.

Especially as working with artifact files is so opaque (e.g., to find a non-qiime workaround for filtering and importing back into qiime)... this is a major obstacle right now for working with real data sets.

**Comment by gregcaporaso** [comment]
I agree, we need this for the next releases (which will happen before the
phx workshop). This should be a relatively straightforward one to write. It
came up multiple times in Iceland.
