### ISSUE TITLE
Bump to BIOM 2.1.6

### ISSUE THREAD

**Issue by wasade** [qiime2/q2-feature-table#144]
QIIME2 currently depends on BIOM 2.1.5. Bumping to 2.1.6 (see [changelog](https://github.com/biocore/biom-format/blob/master/ChangeLog.md#biom-216) would bring in a few useful additions such as `Table.rankdata`, `Table.concat`, and `Table.del_metadata` while also resolving a few nagging bugs in the HDF5 handling.

**Comment by jairideout** [comment]
Done! https://github.com/qiime2/environment-files/tree/master/latest/staging
