### ISSUE TITLE
Change url to microbial nucleotide BLAST for improved taxonomy results

### ISSUE THREAD

**Issue by JTFouquier** [qiime2/q2-feature-table#145]
**Current Behavior**
![screen shot 2017-09-28 at 11 13 15 am](https://user-images.githubusercontent.com/7920357/30980437-5112d8e8-a43e-11e7-9d98-09a9e4af956d.png)

**Proposed Behavior**
Using microbial genomes BLAST url:
![screen shot 2017-09-28 at 11 12 57 am](https://user-images.githubusercontent.com/7920357/30980438-5119ee3a-a43e-11e7-9f56-2066b45ff5fe.png)

**Comments**
Hello! Cathy Lozupone and I were looking at some data and she had this suggestion. Quick fix and would be nice for users to get some microbe names rather than just everything being called uncultured. 

**References**
https://blast.ncbi.nlm.nih.gov/Blast.cgi?PAGE_TYPE=BlastSearch&BLAST_SPEC=MicrobialGenomes

**Comment by lizgehret** [comment]
Closing this out as this limits the application for utilizing BLAST (i.e. for use in human contamination, etc).
