### ISSUE TITLE
BIOM 2.1.6 refactors

### ISSUE THREAD

**Issue by wasade** [qiime2/q2-feature-table#149]
**Improvement Description**
On a review of the codebase, it looks like the following can be refactored to take advantage of new endpoints available in BIOM 2.1.6 once #148 is merged.

- [x] `_filter._filter_table` can use `Table.remove_empty() on these [lines](https://github.com/qiime2/q2-feature-table/blob/2ac9768c94484b82d2397953c16b4560a4b25647/q2_feature_table/_filter.py#L56-L61).
- [x] `_merge.merge` can use `Table.concat`. For two tables, this will be faster. `concat` supports an arbitrary number of `Table` instances though, so API call will become important once variadic arguments are supported (e.g., to allow the user to merge N tables).
- [x] `_sample.sample can use `Table.remove_empty()` [here](https://github.com/qiime2/q2-feature-table/pull/146/files#diff-bf9aec931e0643ae3dfee4bb85f5bb1bR22). Note as of the creation of this issue, this method was in an unmerged PR #146 
 
**References**
1. #148 
2. [lines](https://github.com/qiime2/q2-feature-table/blob/2ac9768c94484b82d2397953c16b4560a4b25647/q2_feature_table/_filter.py#L56-L61)
3. [here](https://github.com/qiime2/q2-feature-table/pull/146/files#diff-bf9aec931e0643ae3dfee4bb85f5bb1bR22)
4. #146

**Comment by lizgehret** [comment]
Going to close this since it isn't mission critical and hasn't been addressed since being opened - but please re-open and address if needed @wasade!

**Comment by wasade** [comment]
I would really recommend fully using the `biom.Table` API as it is optimized. I do not have permissions to reopen this

**Comment by lizgehret** [comment]
Sounds good @wasade I'll re-open, we're open to these improvements if you have time to cut a PR on this!
