### ISSUE TITLE
`filter-seqs`: filter by seq length

### ISSUE THREAD

**Issue by jairideout** [qiime2/q2-feature-table#151]
**Improvement Description**
It'd be useful to have a way to filter sequences based on length -- maybe even an option to trim to a length, but that might be better as its own method. 

**References**
Came up [on the forum](https://forum.qiime2.org/t/adding-read-number-tracking-and-amplicon-size-overview-to-featuretable-summary/1485/6?u=jairideout).

**Comment by nbokulich** [comment]
[forum xref](https://forum.qiime2.org/t/comparison-of-dada2-with-deblur/3503/10?u=nicholas_bokulich)

**Comment by nbokulich** [comment]
The RESCRIPt plugin has a couple actions for filtering sequences by length. So perhaps this issue can be closed as not needed any more? @lizgehret ?

**Comment by lizgehret** [comment]
that makes sense to me @nbokulich!
