### ISSUE TITLE
`filter-seqs` found in a feature table

### ISSUE THREAD

**Issue by nbokulich** [qiime2/q2-feature-table#152]
A few forum posts ([here](https://forum.qiime2.org/t/mock-sample-and-pcr-blanks/1113) and [here](https://forum.qiime2.org/t/filtering-featuredata-sequence-using-metadata-file/1514)) have raised the need for filtering out features found in specific samples, e.g., PCR blanks. It would be useful to have a streamlined method for doing this, e.g., if a feature table could be provided as metadata to `filter-seqs` to extract a list of features to exclude/not exclude.

[This thread](https://forum.qiime2.org/t/mock-sample-and-pcr-blanks/1113) covers a workaround for generating a list of features that can be input as metadata, but involves some "manual" work to get this done on the CLI.

**Comment by ebolyen** [comment]
One "workaround" that I don't think we've written down anywhere is we could have a method which computed the marginal totals for a table on a given axis, creating a FeatureData/SampleData artifact which could be viewed as metadata. This would let you filter down to a row or two, then collapse them into something that could be used as feature metadata.

**Comment by gregcaporaso** [comment]
I helped a user with this today. This would be good to get in place. I worked around it using the Artifact API as follows.

Get some data to work with:
```bash
$ wget https://docs.qiime2.org/2017.10/data/tutorials/moving-pictures/table.qza
$ wget https://docs.qiime2.org/2017.10/data/tutorials/moving-pictures/rep-seqs.qza
$ qiime feature-table filter-features --i-table table.qza --o-filtered-table table-ms5.qza --p-min-samples 5
```

Filter the corresponding `FeatureData[Sequence]` to contain only those features in `table-ms5.qza`.
```python
>>> import qiime2
>>> import pandas as pd
>>> from qiime2.plugins.feature_table.actions import filter_seqs
>>> table = qiime2.Artifact.load('table-ms5.qza').view(pd.DataFrame)
>>> feature_ids = qiime2.Metadata(table.T)
>>> filtered_seqs, = filter_seqs(qiime2.Artifact.load('./rep-seqs.qza'), feature_ids)
>>> filtered_seqs.save('rep-seqs-ms5.qza')

**Comment by thermokarst** [comment]
This came up on the forum, twice: [A](https://forum.qiime2.org/t/filtering-rep-qza-based-on-filtered-feature-table/1917?u=thermokarst), [B](https://forum.qiime2.org/t/how-do-i-create-a-tree-from-a-subset-of-samples/1885?u=thermokarst)

**Comment by gregcaporaso** [comment]
@ebolyen, the methods that you're describing would be super-useful for another reason too - total feature counts would be really handy to be able to include in tabulated metadata. For example, a super-useful table would be, for each feature, tabulate its count, its taxonomy assignment, and its sequence. I've hacked that together a few times so far, but it involves pulling a tsv file of the total counts from `feature-table summarize`.
