### ISSUE TITLE
Missing graph in visualizer after merging feature tables

### ISSUE THREAD

**Issue by JTFouquier** [qiime2/q2-feature-table#153]
I noticed that the graph was missing after merging tables from two runs: 

<img width="1136" alt="screen shot 2017-10-23 at 9 26 23 pm" src="https://user-images.githubusercontent.com/7920357/31923635-e7a67068-b838-11e7-8213-f70fbf97c996.png">

I checked provenance and my merge was performed using release 2017.9, but some of my upstream files were generated using 2017.8. (I wasn't sure if this was a feature-table issue or a q2view issue)

**Comment by jairideout** [comment]
Did you supply `--m-sample-metadata-file` to the `feature-table summarize` command when you generated this visualization? If you omit the metadata, this is the view I'd expect to see.

**Comment by JTFouquier** [comment]
Yes, that was it. I associated the issue with the merge command and missed adding the metadata for the merged table summary. Thanks!
