### ISSUE TITLE
tabulate-seqs: include abundances?

### ISSUE THREAD

**Issue by thermokarst** [qiime2/q2-feature-table#158]
**Improvement Description**
Optionally provide a feature table to `tabulate-seqs` to learn about abundances.

**References**
This came up [on the forum](https://forum.qiime2.org/t/sort-options-for-rep-seqs-visualization/2136?u=thermokarst).

**Comment by gregcaporaso** [comment]
Closing this in favor of #276 and #282, which together will support integration of this information into the `tabulate-seqs` output.
