### ISSUE TITLE
`total-feature-frequencies` and `total-sample-frequencies` methods

### ISSUE THREAD

**Issue by gregcaporaso** [qiime2/q2-feature-table#161]
**Improvement Description**
@ebolyen suggested the following in #152 - copying that here as the suggestion would be generally useful, though it isn't used in the PR that is fixing that issue:

> we could have a method which computed the marginal totals for a table on a given axis, creating a FeatureData/SampleData artifact which could be viewed as metadata.

I replied with the following:

> The methods that you're describing would be super-useful for another reason too - total feature counts would be really handy to be able to include in tabulated metadata. For example, a super-useful table would be, for each feature, tabulate its count, its taxonomy assignment, and its sequence. I've hacked that together a few times so far, but it involves pulling a tsv file of the total counts from feature-table summarize.

For the feature axis, it would be useful to have both the total frequency and the number of samples containing the feature. For the sample axis, it would be useful to have both the total frequency and the number of observed features (i.e., the "observed-otus" metric - edit: though this could be misleading if it wasn't computed on a rarified table). 

**Comments**
1. This is related to the request in #158 too.
2. I think you'd need two methods for this, since the outputs would be different for the different axes (e.g., `FeatureData[Frequency]` or `SampleData[Frequency]`). 

**References**
1. #152
2. #158

**Comment by ChrisKeefe** [comment]
Adding "download as csv" links to `feature-table summarize`'s Sample and Feature detail pages could mirror this functionality in a quick/dirty way.

**Comment by thermokarst** [comment]
> Adding "download as csv" links to feature-table summarize's Sample and Feature detail pages could mirror this functionality in a quick/dirty way.

Like this?

<img width="836" alt="Screen Shot 2020-11-16 at 1 07 55 PM" src="https://user-images.githubusercontent.com/274668/99302641-e1538d80-280c-11eb-885d-6492172517ce.png">

**Comment by ChrisKeefe** [comment]
Ha! That's _exactly_ what I had in mind, @thermokarst. Why did we put those links on the summary tab, instead of the tabs with the details on them? Not that it matters, really, but it feels less intuitive to me this way.

**Comment by thermokarst** [comment]
> Why did we put those links on the summary tab, instead of the tabs with the details on them?

I think the CSV links predate the individual tabs (https://github.com/qiime2/q2-feature-table/blob/222ec9329d34c88087eb0ad5960d13611dcb2396/q2_feature_table/assets/summarize.template#L75), so probably just an omission. I think adding links in on the individual tabs would be a great addition!

**Comment by ChrisKeefe** [comment]
Spun this lil discussion off into a separate [issue](https://github.com/qiime2/q2-feature-table/issues/240)

**Comment by gregcaporaso** [comment]
Closing this in favor of https://github.com/qiime2/q2-feature-table/issues/282, which will output this information as part of the `summarize` action.
