### ISSUE TITLE
`summarize`: add list of sample IDs that features are observed in to feature detail

### ISSUE THREAD

**Issue by nbokulich** [qiime2/q2-feature-table#165]
**Improvement Description**
This could be a bit cumbersome in the current viz unless if we could add a collapsible list of sample IDs. 

A separate visualizer might be an alternative... e.g., some sort of interactive table explorer?

**References**
[forum xref](https://forum.qiime2.org/t/figuring-out-samples-an-otu-belongs-to/2738)

**Comment by lizgehret** [comment]
Closing this in favor of @Clockwork-Rat's PR #285.
