### ISSUE TITLE
`summarize` accepts non-frequency tables as input

### ISSUE THREAD

**Issue by ebolyen** [qiime2/q2-feature-table#166]
**Improvement Description**
However, most of the tabs/reports don't really make sense. Maybe they should be adjusted, or perhaps only `FeatureTable[Frequency]` should be permitted. 

**References**
Original [forum post](https://forum.qiime2.org/t/relative-abundance-output-problem/2904).

**Comment by antgonza** [comment]
Just saw this issue as I tried to summarize a FeatureTable[Composition] and got the error below. I _think_ the possibility of passing other types is powerful (*) but agree that RelativeFrequency is kind of odd and perhaps the solution is to deal differently in the summary when doing RelativeFrequency vs. others, which can also create other per type problems like different kinds of composition changes in FeatureTable[Composition].

(*) For example, while dealing with metabolomic data, I needed to plot a few times the PresenceAbsence table so I could figure out sample removing based on number of peaks in the samples.

```
Plugin error from feature-table:

  Argument to parameter 'table' is not a subtype of FeatureTable[Frequency | PresenceAbsence | RelativeFrequency].
```

**Comment by gregcaporaso** [comment]
Closing this as we now have support for RelativeFrequency and PresenceAbsence. Composition seems to be it's own beast, and if this is still an operation that is needed it probably makes sense to do this in its own action (either in q2-feature-table or q2-composition).
