### ISSUE TITLE
`filter-samples`: improve error message when samples are not present in table

### ISSUE THREAD

**Issue by nbokulich** [qiime2/q2-feature-table#168]
**Comments**
1. In [this forum post](https://forum.qiime2.org/t/feature-table-summarize-nan-error/3397) a user describes an incomprehensible error that was caused by trying to filter out samples that were not actually in a feature table.
2. That error message should probably be improved, if that is indeed the root cause.

**Comment by thermokarst** [comment]
Just to clarify, the error message is being emitted from `summarize`, not `filter-samples`.

**Comment by gregcaporaso** [comment]
Came across this issue while looking for another one. This seems to be addressed now. 

In this case, `metadata.tsv` doesn't contain one of the sample ids that is in `table.qza`:
```bash
$ qiime feature-table summarize \
    --i-table table.qza \
    --o-visualization table.qzv \
    --m-sample-metadata-file metadata.tsv

Plugin error from feature-table:

  The following IDs are not present in the metadata: 'L1S281'

Debug info has been saved to /var/folders/jp/_7s6840d2gdf_gkg1291p7x00000gn/T/qiime2-q2cli-err-ygofoa45.log
```

I also confirmed that this isn't an issue for `filter-samples`:
```
$ qiime feature-table filter-samples --i-table table.qza --m-metadata-file metadata.tsv --o-filtered-table table-filt-1.qza
Saved FeatureTable[Frequency] to: table-filt-1.qza

$ qiime feature-table filter-samples --i-table table.qza --m-metadata-file metadata.tsv --o-filtered-table table-filt-1.qza --p-exclude-ids
Saved FeatureTable[Frequency] to: table-filt-1.qza

```
