### ISSUE TITLE
Allow for no clustering on either axis of heatmap viz

### ISSUE THREAD

**Issue by nbokulich** [qiime2/q2-feature-table#173]
The `heatmap` viz supports axis clustering when plotting - this issue proposes adding a new option to the existing available options.

**Current Behavior**
Current options are to cluster samples, features, or both samples and features (options `samples`, `features`, `both`, respectively).

**Proposed Behavior**
It would be nice to also support generating this viz with no clustering applied to the axes (`cluster='none'`). This would render the IDs in the same order that they are in in the `biom.Table` used to generate the viz.

**Questions**
1. The current default for the `cluster` parameter is `both`, and it seems like it makes sense to leave that value unchanged with the addition of the `none` option.

**References**
1. [Original forum post](https://forum.qiime2.org/t/feature-table-heatmap-with-no-clustering-on-neither-axes/3826?u=nicholas_bokulich)
2. [Another request on the forum](https://forum.qiime2.org/t/heat-map-issues/3980)

**Comment by thermokarst** [comment]
This recently [came up on the forum](https://forum.qiime2.org/t/heat-map-issues/3980).

**Comment by gwarmstrong** [comment]
I'll handle this one
