### ISSUE TITLE
feature-request: filter table via another table

### ISSUE THREAD

**Issue by antgonza** [qiime2/q2-feature-table#174]
**Improvement Description**
It will be really nice if we could filter a feature-table qza via another qza and/or via a txt list of sample names.

**Current Behavior**
The particular use case, but I guess there can be others, is:
After multiple iterations of alpha/beta you end up with a rarefied qza that becomes your final table. Now, you want to do another analysis (for example differential abundance) and need to filter your un-rarefied table. Currently, you have to do run multiple commands to accomplish this.

**Proposed Behavior**
My solution unzip the qza, summarize table via biom, get the list parse it and generate a --p-where with those values ...

**Comment by thermokarst** [comment]
Thanks @antgonza!

@ebolyen, I imagine this particular use-case could be handled if we get around to viewing `FeatureTable`s as metadata, eh? If we had that "collapse-along-an-axis" escape hatch, that could work too.

**Comment by gregcaporaso** [comment]
Just noticed this issue while looking for another one. I just confirmed that this is supported now:

Here `metadata.tsv` has a subset of the samples in `table.qza`. The resulting `table-filt-1.qza` has only the samples in `metadata.tsv`.  

```bash
 qiime feature-table filter-samples \
    --i-table table.qza \
    --m-metadata-file metadata.tsv \
    --o-filtered-table table-filt-1.qza
```

Filtering the original `table.qza` file by passing the feature table from the previous step (`table-filt-1.qza`) as metadata results in a new feature table (`table-filt-2.qza`) that only contains the samples in `table-filt-1.qza`. 

```bash
qiime feature-table filter-samples \
    --i-table table.qza \
    --m-metadata-file table-filt-1.qza \
    --o-filtered-table table-filt-2.qza
```
