### ISSUE TITLE
Feature request - display number of samples in category

### ISSUE THREAD

**Issue by antgonza** [qiime2/q2-feature-table#180]
**Improvement Description**
In the `summarize` viz, display information about number of samples in a given category. This should include total samples in category, and the number of samples at a given rarefaction depth.

**Current Behavior**
The sample information (total & remaining at a sampling depth) are present in graphical form on the plot.

**Proposed Behavior**
The new viz should include a text description of the sample info.

<img width="1312" alt="screen shot 2018-07-09 at 10 36 01 am" src="https://user-images.githubusercontent.com/2014559/42463851-9c576ba6-8364-11e8-8940-4d4cd1d4970a.png">

**Comment by thermokarst** [comment]
Fixed in #209
