### ISSUE TITLE
`filter-features` should not drop empty samples by default

### ISSUE THREAD

**Issue by nbokulich** [qiime2/q2-feature-table#184]
**Current Behavior**
After filtering features, "Any samples with a frequency of zero after feature filtering will also be removed." [according to the docs](https://docs.qiime2.org/2018.6/plugins/available/feature-table/filter-features/)

This is problematic, e.g., if you want to filter based on a particular taxon or other feature metadata and then use alpha div or build a heatmap of that subset of features.

**Proposed Behavior**
Should add a parameter to choose whether or not empty samples should be dropped, or even a threshold (at that point making a pipeline that filters samples and features might be a better solution). Otherwise, don't drop empty samples. 

Issuing a warning even just to stdout could also be useful, indicating the # and IDs of samples that were dropped.

**References**
1. [according to the docs](https://docs.qiime2.org/2018.6/plugins/available/feature-table/filter-features/)
2. [forum xref](https://forum.qiime2.org/t/feature-table-filter-features-keep-samples-for-heatmap/5457)

**Comment by gregcaporaso** [comment]
Looks like this was addressed [here](https://github.com/qiime2/q2-feature-table/commit/6ba8036ab7071a2df2813d46148c4770a493533f) (see the `--p-filter-empty-samples` parameter).
