### ISSUE TITLE
`filter-samples` should not drop empty features by default

### ISSUE THREAD

**Issue by nbokulich** [qiime2/q2-feature-table#185]
**Current Behavior**
After filtering samples, "Any features with a frequency of zero after sample filtering will also be removed." [according to the docs](https://docs.qiime2.org/2018.6/plugins/available/feature-table/filter-samples/)

Silently dropping these features might be undesirable to some users.

**Proposed Behavior**
Should add a parameter to choose whether or not empty features should be dropped, or even a threshold (at that point making a pipeline that filters samples and features might be a better solution). Otherwise, don't drop empty features. 

Issuing a warning even just to stdout could also be useful, indicating the # and IDs of features that were dropped.

**References**
1. [according to the docs](https://docs.qiime2.org/2018.6/plugins/available/feature-table/filter-samples/)
2. [forum xref](https://forum.qiime2.org/t/feature-table-filter-samples/5323)

**Comment by sejsong** [comment]
I like that this is the default, although I guess having it as an option wouldn't hurt. Out of curiosity, what are scenarios where this wouldn't be desirable?

**Comment by nbokulich** [comment]
I'm just speculating: if looking at a subset of samples, it could be useful to explicitly see which features are zero abundance in that subset.

But I agree, I think that dropping zero-abundance features is the more useful default (as it is currently).

**Comment by fedarko** [comment]
Just to update, this has come up in another forum discussion [here](https://forum.qiime2.org/t/filtering-method-for-featuredata-differential/15553). The empty filtering behavior can mess up [Qurro](https://github.com/biocore/qurro) in certain cases, as described in that thread.

**Comment by dwthomas** [comment]
I got around to implementing this as an option (default behavior remains the same).  A philosophical argument for changing the default would be that filtering nothing should be an identity operation.  
And most of my use cases are what @nbokulich above, for example if I filter my data by month, those columns of zeros have a different interpretation than a non existent feature.  (we detect this feature elsewhere in the experiment, but not here).
