### ISSUE TITLE
`summarize` frequency per feature details csv ≠ html

### ISSUE THREAD

**Issue by nbokulich** [qiime2/q2-feature-table#187]
**Improvement Description**
The frequency per feature detail csv downloaded from this visualization should contain the same "# of Samples Observed In" data column found in the html summary.

**Current Behavior**
The current download is missing the "# of Samples Observed In" data column found in the html summary. E.g., see [the moving pics example](https://view.qiime2.org/visualization/?type=html&src=https%3A%2F%2Fdocs.qiime2.org%2F2018.8%2Fdata%2Ftutorials%2Fmoving-pictures%2Ftable.qzv)

**Proposed Behavior**
Add that column to the downloaded data.

**References**
1. [the moving pics example](https://view.qiime2.org/visualization/?type=html&src=https%3A%2F%2Fdocs.qiime2.org%2F2018.8%2Fdata%2Ftutorials%2Fmoving-pictures%2Ftable.qzv)
2. [forum xref](https://forum.qiime2.org/t/feature-frequency-detail-csv-should-include-of-samples-observed-in/5885)

**Comment by Oddant1** [comment]
This is superseded by #282. This info is now available in the outputs from `summarize_plus` pipeline.
