### ISSUE TITLE
New method: transpose

### ISSUE THREAD

**Issue by thermokarst** [qiime2/q2-feature-table#195]
**Addition Description**
A new method should be added, `transpose`. This will accept a feature table as input and return the transposed feature table as output. This, coupled with the ability to view the sample axis of a `FeatureTable` as `Metadata` will allow users to work with both axes as `Metadata`.

**References**
1. https://github.com/qiime2/q2-types/pull/186

**Comment by turanoo** [comment]
Will the output of this method be of type `FeatureTable[Frequency]'?? Or is there any special type for transposed feature tables?

**Comment by thermokarst** [comment]
Yep, let's start with accepting a `FeatureTable[Frequency]` and returning a `FeatureTable[Frequency]`. Once we have `TypeMap` we can add other types, as well.

Something for future discussion (not something to worry about in this immediate project):
We could use type properties to indicate that the feature table has been transposed. cc @ebolyen
