### ISSUE TITLE
PendingDeprecationWarning for `numpy` `matrix` subclass

### ISSUE THREAD

**Issue by gwarmstrong** [qiime2/q2-feature-table#207]
**Bug Description**
There are a good number of lines (~62 in my fork) of the form:

```
return matrix(data, dtype=dtype, copy=False) 
```

that trigger a `PendingDeprecationWarning`:

```
numpy/matrixlib/defmatrix.py:68: PendingDeprecationWarning: the matrix subc
lass is not the recommended way to represent matrices or deal with linear algebra 
(see https://docs.scipy.org/doc/numpy/user/numpy-for-matlab-users.html). Ple
ase adjust your code to use regular ndarray.    
```

**Steps to reproduce the behavior**
1. Clean install of `q2-feature-table`
2. Run tests
3. See warnings

**Expected behavior**
The code should be updated to reflect this deprecation.

**Computation Environment**
- OS: macOS El Capitan
- QIIME 2 Release 2019.1

**Comment by thermokarst** [comment]
Thanks for the report @gwarmstrong, but, I _think_ this might be on the wrong repo... Those warning appear to be coming from the [biom project](https://github.com/biocore/biom-format/).

**Comment by thermokarst** [comment]
Just to clarify, this plugin uses biom extensively (it is basically just a big wrapper around biom), but, I think the fixes might need to happen there, instead. With that said, we should definitely confirm that we aren't directly using this deprecated API here, too!

**Comment by gwarmstrong** [comment]
Good catch that it is not in this repo. After a little more digging, I am pretty sure this is not really an issue in biom-format either, per se. Instead it seems to actually be cascading from some unresolved issues in scipy: https://github.com/scikit-learn/scikit-learn/issues/12327
