### ISSUE TITLE
Partially using a mapping file leads to an empty table

### ISSUE THREAD

**Issue by ElDeveloper** [qiime2/q2-feature-table#215]
**Bug Description**
Using a mapping file without the where clause will lead to an empty table in `filter-features`.

**Steps to reproduce the behavior**

```bash
# filter a table based on frequency with a mapping file as part of the
# arguments but without any WHERE clause
qiime feature-table filter-features \
--i-table feature-table.qza \
--p-min-frequency 10 \
--m-metadata-file mapping-file.tsv \
--o-filtered-table empty.what.qza

# this results in an empty table
qiime feature-table summarize \
--i-table empty.what.qza \
--o-visualization empty.what.qzv

qiime tools view empty.what.qzv
```

If I remove the `--m-metadata-file` flag from the filter-features command things work as expected.

**Expected behavior**
An empty table should not be produced.

**Computation Environment**
macOS

**Comment by thermokarst** [comment]
Thanks @ElDeveloper! So the `filter-*` actions are _designed_ to work without the `where` clause in place --- if there is no `where`, the actions will perform a simple ID match. Any chance your `mapping-file.tsv` just didn't have any of the feature IDs found in `feature-table.qza`?

**Comment by thermokarst** [comment]
I put together a MWE of what I mentioned above, demonstrating the "no where-clause" behavior that is _intended_ (ah, intent vs action, the boundary between the two when writing code is often elusive)...

```bash
$ wget https://docs.qiime2.org/2019.4/data/tutorials/moving-pictures/table.qza
$ wget https://docs.qiime2.org/2019.4/data/tutorials/moving-pictures/taxonomy.qza

# count number of features in original table
$ qiime tools inspect-metadata table.qza --tsv | wc -l | awk '{print $1-1}'
770

# Will view `FeatureData[Taxonomy] as Metadata in the following:
$ qiime feature-table filter-features \
  --i-table table.qza \
  --p-min-frequency 10 \
  --m-metadata-file taxonomy.qza \
  --o-filtered-table filtered-table.qza

# count number of features in table filtered with taxonomy
$ qiime tools inspect-metadata filtered-table.qza --tsv | wc -l | awk '{print $1-1}'
554

# create new MD file with IDs that don't match, for example, maybe these are sample IDs?
$ echo 'id\nfoo\nbar\nbaz' > different_id_set.tsv

$ qiime feature-table filter-features \
  --i-table table.qza \
  --p-min-frequency 10 \
  --m-metadata-file different_id_set.tsv \
  --o-filtered-table filtered-table-bad.qza

# count number of features in table filtered with mismatched IDs
$ qiime tools inspect-metadata filtered-table-bad.qza
An error has been encountered:

  Metadata must contain at least one ID.
```

Does this maybe explain what you are seeing above? If not, do you have some data you could share? Thanks! :call_me_hand:

**Comment by ElDeveloper** [comment]
> Any chance your mapping-file.tsv just didn't have any of the feature IDs found in feature-table.qza?

Yes, you are correct. This solves this problem, I see where my misunderstanding is. 👍
