### ISSUE TITLE
Add method to re-name features or samples in feature table

### ISSUE THREAD

**Issue by nbokulich** [qiime2/q2-feature-table#223]
**Addition Description**
Given a sample metadata file/column and a feature table, re-name the feature table to use the labels in the specified column instead.

**Current Behavior**
This can be achieved with `feature_table.group()` in a roundabout way — and it is slow since the method is grouping and summing instead of just re-indexing. Having a dedicated method to this often-requested feature (based on forum requests) would be ideal.

**Proposed Behavior**
`biom.Table.update_ids()` the chosen feature table axis (sample/feature) using the provided metadata. Need to add some basic validation/processing:
1. ensure that all values in the metadata column are unique
2. re-order the metadata index to match the order in the table

**Questions**
1. What if metadata is a superset? Probably just ignore the extra IDs.
2. What if metadata is a subset? error or only relabel that subset of IDs? (I think both: add a parameter to adjust missing ID handling, which would be error by default)

**Comment by jwdebelius** [comment]
I know we talked about this a month ago, and I want to test the waters with plugins before I try to build my own. So, one question is whether we should take a metadata column as input or just a tsv kind of map.

**Comment by thermokarst** [comment]
I think it should be a metadata column (which QIIME 2 interfaces like q2cli can extract from a metadata tsv file).
