### ISSUE TITLE
Summarize visualizer gives distorted barplot shapes when switching between metadata categories

### ISSUE THREAD

**Issue by mestaki** [qiime2/q2-feature-table#224]
**Bug Description**
Interactive Sample Detail tab:  when changing the metadata categories that re-sorts the barplots, you occasionally get distorted barplot shapes which seem to be residues from the previous category.

**Steps to reproduce the behavior**
Two feature-tables made using older version of Q2 (2018.6) were merged with 2019-10. Not sure if this issue is related to those older feature-tables or not.

**Expected behavior**
No width distortion on barplots when changing categories.

**Screenshots**
Shown below with Chrome, Version 79.0.3945.130, (64-bit), q2-2019-10.
Sorry about the slow-gif <- occurred during conversion.
![table-summarize-viz-buggy](https://user-images.githubusercontent.com/17439092/75723481-45d7b800-5c91-11ea-810b-39ed90f262f7.gif)

**Comment by thermokarst** [comment]
Thanks @mestaki! Do you have a sample QZV or `FeatureTable[Frequency]` + `Metadata` for us to recreate and interrogate? You can DM/email me the data. Thanks!

**Comment by mestaki** [comment]
Sure, just emailed them to you.

**Comment by thermokarst** [comment]
Thanks @mestaki - I was able to reproduce locally. I generated an MVP using the following:

```python
import qiime2
import pandas as pd

from qiime2.plugins import feature_table as ft_plugin


table_data = pd.DataFrame([[1, 2, 3], [4, 5, 6], [7, 8, 9]],
                          index=['s1', 's2', 's3'],
                          columns=['f1', 'f2', 'f3'])
md_data = pd.DataFrame([["Yes", "No"], ["No", "Yes"], ["Yes", "No"]],
                       index=pd.Index(['s1', 's2', 's3'], name='id'),
                       columns=["foo", "bar"])
table = qiime2.Artifact.import_data('FeatureTable[Frequency]',
                                    table_data, view_type=pd.DataFrame)
md = qiime2.Metadata(md_data)
viz, = ft_plugin.visualizers.summarize(table, md)
viz.save('mvp.qzv')
```

The issue here appears to be related to "recycling" x-axis groups when changing between metadata columns. I suspect the vega code has some code in the "update" hook that actually needs to be in an "enter" - or vice versa.

Anyone interested in learning vega??
