### ISSUE TITLE
IMP: `merge` should accept other feature table types

### ISSUE THREAD

**Issue by nbokulich** [qiime2/q2-feature-table#238]
**Improvement Description**
`merge` should accept multiple feature table types, at least `RelativeFrequency` as well as `Frequency`

**Current Behavior**
`merge` only accepts `List[FeatureTable[Frequency]]`

**Proposed Behavior**
Support `RelativeFrequency` and maybe other types. Use `TypeMap` to map the inputs to the outputs (should be the same type)

**Questions**
1. Is `TypeMap` enough to solve this? It seems like a transformer might need to be added to convert to other types (e.g., relative frequency) when outputting, since right now `merge` just sums the values.

**Comment by thermokarst** [comment]
`FeatureTable[RelativeFrequency]` support was added in #242

**Comment by gregcaporaso** [comment]
Closing this, as we now support `RelativeFrequency` and `PresenceAbsence`. @nbokulich, feel free to re-open if there is another type you think we should be supporting right now.
