### ISSUE TITLE
Add download csv links to Feature Detail and Interactive Sample Detail tabs

### ISSUE THREAD

**Issue by ChrisKeefe** [qiime2/q2-feature-table#240]
**Improvement Description**
Add download csv links to:
- Feature Detail tab
- Interactive Sample Detail tab

to allow users to download the data displayed in those tables.

**Current/Proposed Behavior**
Links to these two csvs _already exist_ on the Overview tab, but should probably be added to the tabs where the data is actually presented. As it is, they're pretty easy to overlook.

For the sake of simplicity and not confusing anyone who already uses the current links, I'm inclined to leave them where they are and duplicate on the other tabs. 

**References**
Initially discussed [here](https://github.com/qiime2/q2-feature-table/issues/161#issuecomment-729270787).

**Comment by Oddant1** [comment]
This is superseded by #282. The csvs are now produced as output by the `summarize_plus` pipeline.
