### ISSUE TITLE
Update 'master' branch name to 'main'

### ISSUE THREAD

**Issue by sabahzero** [qiime2/q2-feature-table#254]
Reasoning and execution:
https://stevenmortimer.com/5-steps-to-change-github-default-branch-from-master-to-main/

**Comment by thermokarst** [comment]
Hi @sabahzero, we have been creating new repos in our org using the name `main` as the default branch, but circling around to updating the _existing_ repos is still on our TODO list (it involves coordination with our various other infrastructure elements).

I'm dropping this resource here for our future reference: https://github.com/github/renaming

Thanks!

**Comment by gregcaporaso** [comment]
This one is taken care of now, as we renamed `master` on all of our repos to `dev`.
