### ISSUE TITLE
Update table heading in `feature-table summarize` result

### ISSUE THREAD

**Issue by gregcaporaso** [qiime2/q2-feature-table#270]
We have some inconsistent terminology in the `feature-table summarize` results. 

In the _Overview_ tab, we label the column on the bottom right "Frequency":
![Screenshot 2023-02-03 at 2 13 34 PM](https://user-images.githubusercontent.com/192372/216712075-6534467e-1517-4d5c-a17a-1c43819a34be.png)

<hr>

Similar in the _Feature_ tab:
![Screenshot 2023-02-03 at 2 13 45 PM](https://user-images.githubusercontent.com/192372/216712033-7f7eb500-ed96-4c45-a9b9-1400702e5c07.png)

<hr>

But in the _Sample_ tab, we call this same information _Feature Count_:
![Screenshot 2023-02-03 at 2 13 24 PM](https://user-images.githubusercontent.com/192372/216712090-4d6709b7-39c5-4f5f-8817-88504302848c.png)

<hr>

We should change _Feature Count_ to _Frequency_ here for consistency.

**Comment by Oddant1** [comment]
Should this issue be closed?
