### ISSUE TITLE
`transpose` should support `FeatureTable[RelativeFrequency]`

### ISSUE THREAD

**Issue by gregcaporaso** [qiime2/q2-feature-table#272]
Currently it only supports `FeatureTable[Frequency]`.

This would have helped address a user's request on the forum [here](https://forum.qiime2.org/t/keep-asv-ids-when-converting-to-relative-abundance/25995/4).

**Comment by Oddant1** [comment]
I believe this was closed bt #273. If I'm wrong, we can reopen
