### ISSUE TITLE
add optional inputs to `tabulate-seqs`

### ISSUE THREAD

**Issue by gregcaporaso** [qiime2/q2-feature-table#276]
To assist with assessing why ASVs aren't being assigned taxonomy (one of many [forum x-refs](https://forum.qiime2.org/t/most-of-its-asvs-map-to-other-60/26923/2)), it would be useful if we could optionally provide `FeatureData[Taxonomy]` ~~(and maybe also `FeatureTable[Frequency]`)~~ to the `tabulate-seqs` visualizer. This would add the taxonomy as a new column in the table that is generated by `tabulate-seqs`, making it easier to identify the sequences that are getting poor taxonomy assignments. ~~If the `FeatureTable[Frequency]` was also provided as input, we could also add the number of times each ASV was observed, and the number of samples each ASV was observed in.~~ 

Update: rather than taking a `FeatureTable` directly, this action should take feature metadata as input. This allows for arbitrary metadata to be integrated in the resulting visualization, including the number of times each ASV was observed, and the number of samples each ASV was observed in which will be new `ImmutableMetadata` outputs from `summarize` following #282. This information is useful for example to help users to prioritize ASVs that are common for further investigation.

**Comment by Oddant1** [comment]
@gregcaporaso this should probably be closed by #284, but I'll let you look at things and close this or request further changes when you get the chance.

**Comment by gregcaporaso** [comment]
@Oddant1, @Clockwork-Rat - thanks so much for the work on this. I downloaded and tested #284, and it's working great. 

A few (little?) requests before we close this one out:
1. I think we may have talked about this in person and I forgot to write it down in the issue. Could you drop the Confidence scores from this visualization? I don't think they're useful in this context. 
2. What do you think of making the `FeatureData[Taxonomy]` into a `List` type, so more than one could be added? This is often of interest when a user is comparing a few taxonomy databases or classifiers (e.g., I showed the .qzv I generated to @cherman2, and her first question was if she could provide more than one taxonomy). The hard part there is how to differentiate them in the visualization - maybe a starting point could be just to name them based on their order in the list if more than one is provided (e.g., `Taxon: 0`, `Taxon: 1`, ...). If only one FeatureData[Taxonomy] is provided as input, just leave it as `Taxon`. This isn't ideal, but I think the folks who would actually use this would be happy enough to have the functionality that they'd be willing to track this on their own until we have a better solution.
3. Would it be possible to add a search/filter box, like we have for [the taxonomy visualizer](https://view.qiime2.org/visualization/?type=html&src=https%3A%2F%2Fdocs.qiime2.org%2F2023.7%2Fdata%2Ftutorials%2Fmoving-pictures%2Ftaxonomy.qzv)? 

**EDIT** (one more):
4. Would it be straight-forward to add sorting on all fields (also as in that .qzv I linked to above)?

**Comment by Oddant1** [comment]
@gregcaporaso we can make the taxonomies a collection instead of a list. Then they can key them if they want or just leave them unkeyed and the keys will default to numbers.

**Comment by Oddant1** [comment]
Now closed by @Clockwork-Rat
