### ISSUE TITLE
sample ids not displayed in summarized feature table

### ISSUE THREAD

**Issue by gregcaporaso** [qiime2/q2-feature-table#303]
Using the *Moving Pictures* tutorial feature table and sample metadata, the displayed per-sample counts in the `feature-table summarize` (and `summarize-plus`) visualizations doesn't have the sample ids, but rather what looks like default `pandas.Index` values. This can be reproduced as follows with those inputs: 

```
qiime feature-table summarize --i-table table.qza --m-sample-metadata-file sample-metadata.tsv --output-dir out
```

Here's a screenshot of the output:

<img width="1607" alt="Screenshot 2024-02-22 at 10 34 50 AM" src="https://github.com/qiime2/q2-feature-classifier/assets/192372/cc8a8246-ef2f-4dba-84bb-260057f97bb1">

Also note that the highlighting seems to be off (three rows are red, when four should be), and the samples are sorted by ascending counts (rather than descending counts).

**Comment by nush320** [comment]
Hello, is this issue fixed? I am not sure I understand how to make my Sample IDs appear instead of the Index,

**Comment by gregcaporaso** [comment]
Hi @nush320, it is fixed and will be in a patch release that's coming out shortly. Keep an eye on the forum and we'll announce when that's ready, it should be next week at the latest. Sorry for the trouble!

**Comment by nush320** [comment]
Thank you! No worries. :))
