### ISSUE TITLE
replace all occurrences of "count" with "frequency" 

### ISSUE THREAD

**Issue by gregcaporaso** [qiime2/q2-feature-table#40]

**Comment by jairideout** [comment]
This shouldn't have been closed by #42 (@gregcaporaso, the text "partially fixes \<issue-number\>" is parsed by GitHub as "fixes \<issue-number\>". I usually write something like "fixes part of \<issue-number\>" or "addresses part of \<issue-number\>").

**Comment by gregcaporaso** [comment]
> the text "partially fixes <issue-number>" is parsed by GitHub as "fixes <issue-number>".

thanks!
