### ISSUE TITLE
filter-features additional functionality

### ISSUE THREAD

**Issue by nbokulich** [qiime2/q2-feature-table#43]
I apologize if the following is already planned, or if I have misunderstood what this method is actually doing. It is also possible that some of what I have written below is possible with `where` clauses — in which case I recommended documenting each of these cases when docs are released, as I believe these could be fairly standard uses.

**Input:** this method only accepts `FeatureTable[Frequency]`. It would be great to use on `FeatureTable[RelativeFrequency]`, e.g., for filtering by relative abundance.

**Filtering Criteria:** this method currently only filters on min/max frequency SUMs for a given OTU, which is useful for many situations (e.g., remove all singletons) but not all. A few other cases that would be useful:
1) Relative frequencies: filter by relative frequencies. This is useful for many cases, and both sum abundance and the criteria suggested below should be applicable to either freq or relative freq
2) min/max average freq/relative freq: e.g., remove features that comprise <1% average abundance across samples
3) min/max minimum freq/relative freq: e.g., remove features that are not detected at a minimum of 5% in at least one sample, or remove features detected at more than 5% relative abundance in at least one sample (the latter is probably less useful, but who knows).
4) min/max maximum freq/relative freq: e.g., remove features that are not detected at 5% in at least one sample, or those that are detected above a certain maximum threshold. The former is a very useful method, e.g., for filtering before making taxonomy barplots, so that only taxa that are abundant in at least one sample are shown.

**What to do with filtered features?:** In relative frequency tables, it may be useful to keep relative frequencies intact after filtering, e.g., if a user wants to view abundant taxa on a barplot without altering actual relative frequencies (e.g., filtered groups will appear as empty space or as "Other"), or focus on specific clades without altering relative frequencies. Both of these examples relate to taxonomy tables, so may be more relevant for `q2-taxa` `barplots` instead...

**Comment by gregcaporaso** [comment]
[forum x-ref](https://forum.qiime2.org/t/filter-feature-table-based-on-percent-prevalent/3499)

**Comment by nbokulich** [comment]
[forum xref](https://forum.qiime2.org/t/filter-features-based-on-proportion/4535)

**Comment by mestaki** [comment]
[form xref ](https://forum.qiime2.org/t/relative-abundances-of-taxonomy-analysis/4939/2)

**Comment by lizgehret** [comment]
Closed by #237
