### ISSUE TITLE
filter-features by feature names

### ISSUE THREAD

**Issue by nbokulich** [qiime2/q2-feature-table#44]
Filter a feature table to match a list of feature names. Some scenarios for filtering based on:
1) file containing list of names on separate lines, e.g., your 100 favorite taxa
2) string containing comma-separated list of taxa to keep/remove, e.g, 'chloroplast' (similar to qiime1's [`filter_taxa_from_otu_table.html`](http://qiime.org/scripts/filter_taxa_from_otu_table.html)). This function is really essential when working with host- and especially plant-associated samples (which may contain high levels of chloroplast and mitochondria).
3) somehow pipe in names directly from ANCOM or other statistical tests (this should probably be generalizable so other plugins can follow suit — e.g., ANCOM or other methods need to optionally output a list of feature IDs that can be read to `filter-features` following option 1 above)

The third example is what really got me thinking here — it would be great to take a list of feature IDs from something like ANCOM that are significantly different among groups (for example) and use this to filter feature tables before doing something like PCoA biplots, correlation tests, or additional significance testing.

**Comment by gregcaporaso** [comment]
Thanks @nbokulich. 

1) this is possible now - you can pass a tab-separated text file as the metadata file. If you don't pass `where`, this will be interpreted as a list of ids to keep. 

2) and 3) are both planned - basically many different types of objects with be viewable as a list of ids, and in this context they could be used as a list of ids to keep.

**Comment by jairideout** [comment]
Closing because (1) is solved and we have existing issues (on different repos) for (2) and (3).
