### ISSUE TITLE
interactive exploration of rarefaction depth in table summaries

### ISSUE THREAD

**Issue by jakereps** [qiime2/q2-feature-table#63]
> interactive exploration of rarefaction depth, as we had in q2d2. this would be really helpful to integrate with metadata, so you can determine how many samples of each metadata type a specific depth would filter from your data set

Taken from #24

**Comment by yech1990** [comment]
Is static rarefaction plot available in qiime2? 
I even can't find it in the “Moving Pictures” tutorial.

**Comment by jairideout** [comment]
@yech1990, can you please post this question on the [QIIME 2 forum](https://forum.qiime2.org)? We primarily use the issue trackers for development-related discussion, such as reporting/fixing bugs, and we have the forum for user support / discussion. Thanks!
