### ISSUE TITLE
Typing in Sampling Depth for interactive tab doesn't update

### ISSUE THREAD

**Issue by thermokarst** [qiime2/q2-feature-table#82]
<img width="1499" alt="screen shot 2017-02-13 at 4 33 32 pm" src="https://cloud.githubusercontent.com/assets/274668/22904363/30a6b0ca-f20a-11e6-8b46-a242c10106d4.png">

Copied-and-pasted 4000 into the input field, the plot updates, but not the "Sample Loss" text

**Comment by jakereps** [comment]
Tested, it doesn't trigger at all when manually typing a number.
