### ISSUE TITLE
"Interactive Sample Detail" tab of table summary should include the fraction of reads filtered

### ISSUE THREAD

**Issue by thermokarst** [qiime2/q2-feature-table#84]

**Comment by gregcaporaso** [comment]
Currently we present the fraction of samples that are filtered, but we should also include the fraction of sequences that are retained at a given rarefaction level. This could show up with the *Sample loss* information as seen here:

<img width="535" alt="screenshot 2017-02-18 14 26 37" src="https://cloud.githubusercontent.com/assets/192372/23096261/8966a69a-f5e6-11e6-99ad-677369a88994.png">

Also, for clarity, should we replace the text *Sample loss* with something like:

Fraction (number) of samples that will be retained: 50% (25)
Fraction (frequency) of total frequency that will be retained: 25% (50,001)
