### ISSUE TITLE
port `collapse_samples.py` functionality from QIIME 1

### ISSUE THREAD

**Issue by gregcaporaso** [qiime2/q2-feature-table#86]
This can be used for collapsing replicate groups, or for combining samples that are sequenced in different sequencing runs/lanes.

**Comment by gregcaporaso** [comment]
@nbokulich brought up a use case in #109, and this came up on the forum [here](https://forum.qiime2.org/t/import-paired-end-illumina-data/684).

**Comment by jairideout** [comment]
@gregcaporaso mentioned on Slack that it might make sense to put this functionality in `feature-table merge` instead of a new method.
