### ISSUE TITLE
Shared vs. Unique OTUs

### ISSUE THREAD

**Issue by tcarrie1** [qiime2/q2-feature-table#94]
All,

As an ecologist, quantifying and IDing which microbes are uniquely present in different environments may aid in a functional association with the holobiont. In familiarizing myself with QIIME (not QIIME 2, yet), I've noticed that there is no script for doing so, where, for example, using a mapping file and biom table, the user may quantify the unique as well as shared OTUs between 'treatments' (whether that be geographic location, environmental stress, etc.).

As holobiont or hologenome ecology is becoming an increasingly important in discerning the evolution of holobionts and hologenomes, I write this query to see if there is interest in developing such a script (that, ideally, is compatable with both QIIME and QIIME 2.0).

Regards,
Tyler

**Comment by gregcaporaso** [comment]
Hi @tcarrie1,
I think the Jaccard distance metric provides what you're looking for. It is interpreted as the fraction of features/OTUs that are unique across a pair of samples (and Jaccard similarity would be the inverse of that - the fraction that are shared across a pair of samples). This metric is available through `beta_diversity.py` in QIIME 1, and `qiime diversity beta` and `qiime diversity core-metrics` in QIIME 2. 

In QIIME 1 we also have the `shared_phylotypes.py` script, which will tell you the counts of features/OTUs that are shared between all pairs of samples, but we don't have that functionality in QIIME 2 yet. 

Does that get you what you need? I'm going to close this issue, but if this doesn't answer your question please feel free to re-open it and clarify.
