### ISSUE TITLE
error in Sequences retained calculation

### ISSUE THREAD

**Issue by gregcaporaso** [qiime2/q2-feature-table#97]
Sequences retained should be number of samples retained times even sampling depth, but it's not:

![screenshot 2017-04-19 08 28 20](https://cloud.githubusercontent.com/assets/192372/25188265/5364a826-24da-11e7-9e63-6f30b345a343.png)

**Comment by jairideout** [comment]
Oops -- it's using the original sequence counts instead of the rarefied counts. Good catch! The new calculation makes a lot more sense for determining number of samples vs number of sequences tradeoff. This should be an easy fix to get in for the release.
